# Rank

The **rank**, $r$, of a matrix is the number of pivots produced during elimination.

# Linear Independence

Here are two matrices in $\mathbf{R^3}$

\begin{align}
A &= 
\begin{bmatrix}
1 && 1 && 1 \\
1 && 1 && 0 \\
1 && 0 && 0
\end{bmatrix} &=&
\begin{bmatrix}
\vec{v_1} && \vec{v_2} && \vec{v_3}
\end{bmatrix}
\\
B &= 
\begin{bmatrix}
1 && 1 \\
1 && 1 \\
1 && 0
\end{bmatrix} &=&
\begin{bmatrix}
\vec{v_1} && \vec{v_2}
\end{bmatrix}
\end{align}

The vectors $\vec{v_1}$, $\vec{v_2}$, and $\vec{v_3}$ are **linearly independent** when the only solution to $A\vec{x}=0$ is the zero vector.

In this case, all three vectors are linearly independent. We cannot make any of the three vectors using linear combinations of the others. 

When doing elmination, we get one pivot for every linearly independent column.

Geometrically:
- Dependent vectors in $\mathbf{R^3}$ can lie on a plane (or a line, or the nullspace)
- Three vectors in $\mathbf{R^3}$ that are linearly dependent cannot span all of $\mathbf{R^3}$
- Dependent vectors in $\mathbf{R^2}$ can lie on a line


## Full column rank

The columns of $A$ are linearly independent exactly when every column has a  pivot $r=n$. This could be a tall skinny matrix.

Wide matrices ($n > m$) are gauranteed to have dependent columns.


# Spanning a Space

- A sequence of vectors (such as $\vec{v_1}$, $\vec{v_2}$, and $\vec{v_3}$) **span**  a space.
- For every vector sequence, we can describe the space that those vectors span. 
- That space consists of all linear combinations of the vectors

If we have $n$ linearly independent vectors in $\mathbf{R^n}$, those vectors span $\mathbf{R^n}$. If we have fewer than $n$ linearly in dependent vectors, those vectors span a subspace of $\mathbf{R^n}$.

# Basis for a Vector Space

A **basis** for a vector space is a sequence of independent vectors that span that space.

The vectors $\vec{v_1} \ldots \vec{v_n}$ are a basis for $\mathbf{R^n}$ exactly when they are the columns of an $n$ by $n$ invertible matrix.

- The pivot columns of $A$ are a basis for the column space of $A$
- The pivot rows of $A$ are a basis for the row space
- The pivot rows of the echelon form, $R$,  are a basis for the row space (p. 173)
  - $A$ and $R$ have the same row space, but not the same column space


# Dimension of a Vector Space

The dimension of a space is the number of vectors needed to span that space.

If our subspace in a plane in $\mathbf{R^3}$, the dimension is $2$ (even though we are in $\mathbf{R^3}$).

The dimension of the column space equals the rank of the matrix.


# Dimensions of the Four Subspaces of $A$

The row and the column space have the same dimension.

- If the column space of $A$ is 3 dimensional, the row space is also 3 dimensional
- The dimension of the left nullspace depends on the height of the matrix and the number of pivots

Consider this 4 by 3 matrix:

\begin{equation*}
\begin{bmatrix}
1 && 1 && 1 \\
1 && 1 && 0 \\
1 && 0 && 0 \\
0 && 0 && 0 
\end{bmatrix}
\end{equation*}

\begin{align*}
&\text{Rank} = r &&= 3 \\
&\text{Dimension of the column space} = r &&= 3\\
&\text{Dimension of the row space} = r &&= 3 \\
&\text{Dimension of the null space} = n - r = 3 - 3 &&= 0 \text{ in } \mathbf{R^m} = \mathbf{R^4} \\
&\text{Dimension of the left null space} = m - r = 4 - 3 &&= 1 \text{ in } \mathbf{R^n} = \mathbf{R^3} 
\end{align*}


# Orthogonal Bases

Vectors are **orthonormal** exactly when 

- The length of each vector is $1$, and 
- Each vector is perpendicular to all other vectors in the sequence: $\vec{q_i}^T\vec{q_j} = 0$ when $i \neq j$

A matrix is **orthogonal** when all the column vectors are **orthonormal**.

We call an orthogonal matrix $Q$. Repeating the same explaination above we can describe $Q$ as

$Q^TQ=I$

And when $Q$ is square, $Q^{-1} = Q^T$

$Q^TQ=I$  makes it very easy to project or solve for least squares. When the projection matrix is orthogonal:

- The least squares solution, $A^TA\hat{x}=A^T\vec{b}$ becomes $\hat{x}=Q^T\vec{b}$
- The projection matrix, $P =  A(A^TA)^{-1}A^T$, becomes $QQ^T$



In [16]:
import numpy as np

# This example matrix is taken from p. 233 of Gilbert Strang's textbook
Q = np.matrix([
        [-1,  2,  2],
        [ 2, -1,  2], 
        [ 2,  2, -1]]) * (1/3.)

print(Q * Q.transpose())


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Create Orthonormal Vectors

Start with three independent vectors, $\vec{a}, \vec{b}, \vec{c}$. Convert these vectors to three orthonormal vectors, $A, B, C$.

Leave $\vec{a}$ as it is:

$A = \vec{a}$

Remember how we project a vector onto another vector. To project $\vec{b}$ onto $A$ (assume $A$ is a vector, not a matrix):

$\vec{p} = \dfrac{A^T\vec{b}}{A^TA}A$

If we take the part of $\vec{b}$ that is in the direction of $A$, and subtract it from $\vec{b}$, we will be left with the part of $\vec{b}$ that is orthogonal to $A$.

$B = \vec{b} - \dfrac{A^T\vec{b}}{A^TA}A$

Finally, subtract from $\vec{c}$ the parts of $\vec{c}$ that are orthogonal to $A$ and $B$.

$C = \vec{c} - \dfrac{A^T\vec{c}}{A^TA}A - \dfrac{B^T\vec{c}}{B^TB}B$

Now we have three orthogonal vectors. To make them orthonormal, divide each vector by its length:

\begin{align*}
q_1 = \tfrac{A}{\|A\|}\\
q_2 = \tfrac{B}{\|B\|}\\
q_3 = \tfrac{C}{\|C\|}
\end{align*}
